image: openjdk:8-stretch

stages:
- build
- deploy

build jar:
    stage: build
    script:
    - chmod a+x ./gradlew
    - ./gradlew -Pprod bootJar
    artifacts:
        paths:
        - build/libs/*.jar

push to cloudfoundry:
    stage: deploy
    script:
    - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
    - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
    - ./cf push

