spring:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
server:
  port: 8745
logging:
  file: app.log
  pattern:
    file: "%-5level  %logger{35} - %msg%n"
  level:
    org.isima.tp: ERROR
    root: ERROR
    org.hibernate: ERROR
    org.springframework: ERROR
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
security:
  jwt:
    secret: Cecinestpaslaclefutiliseepourlenvironnementdeproduction!!!!!!!!

